
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: luke-fish-app-project_development

test:
  <<: *default
  database: luke-fish-app-project_test

production:
  <<: *default
  database: luke-fish-app-project_production
  username: luke-fish-app-project
  password: <%= ENV['LUKE-FISH-APP-PROJECT_DATABASE_PASSWORD'] %>
